import type { FormOutcomeType, FormType, GameDate } from '@/types'
import { FORM_DATA, useFormStore } from '@/stores/useFormStore'

export function fileApplicationFromOutcome(formId: string, date: GameDate): boolean {
  const normalized = formId.toLowerCase() as FormType
  if (!(normalized in FORM_DATA)) {
    return false
  }

  try {
    useFormStore.getState().fileApplication(normalized, date)
    return true
  } catch (error) {
    console.warn('Failed to file application from outcome', { formId, error })
    return false
  }
}

export function applyApplicationDecision(
  target: string,
  outcome: FormOutcomeType,
  date: GameDate,
  reason = 'Decision generated by event outcome'
): boolean {
  const formStore = useFormStore.getState()

  // Target may be an application id or form id. Resolve to the most recent matching app.
  let applicationId = target
  const byForm = formStore
    .getActiveApplicationsForForm(target.toLowerCase() as FormType)
    .slice()
    .sort((a, b) => {
      const aValue = a.filedDate.year * 12 + a.filedDate.month
      const bValue = b.filedDate.year * 12 + b.filedDate.month
      return bValue - aValue
    })

  if (byForm.length > 0) {
    applicationId = byForm[0].id
  }

  const app = formStore.getApplication(applicationId)
  if (!app) {
    return false
  }

  formStore.processApplicationDecision(app.id, outcome, reason, date)
  return true
}

export function processMonthlyFormLifecycle(currentDate: GameDate, random: () => number): string[] {
  const formStore = useFormStore.getState()
  const pendingDecisions = formStore.processMonthlyApplications(currentDate, random)

  const decidedApplicationIds: string[] = []
  for (const decision of pendingDecisions) {
    const reason = decision.outcome === 'approved'
      ? 'Application approved after review window'
      : 'Application denied after review window'

    formStore.processApplicationDecision(decision.applicationId, decision.outcome, reason, currentDate)
    decidedApplicationIds.push(decision.applicationId)
  }

  return decidedApplicationIds
}
